require "open-uri"
require "nokogiri"
require "pry"

require_relative "./sea_life/version"
require_relative "./sea_life/concerns/findable.rb"
require_relative "./sea_life/cli"
require_relative "./sea_life/category"
require_relative "./sea_life/scraper"
require_relative "./sea_life/animal"
